version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=cracha_user
      - POSTGRES_PASSWORD=cracha123
      - POSTGRES_DB=cracha_virtual_dev
    ports:
      - "5433:5432"

  backend:
    image: vydhal/eduagenda-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://cracha_user:cracha123@db:5432/cracha_virtual_dev?schema=public
      - JWT_SECRET=cracha_virtual_jwt_secret_key_2023
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    image: vydhal/eduagenda-frontend:latest
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api
